version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/api/nodejs"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/api/golang"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
