ARG NODE_VERSION=18.0.0

FROM node:${NODE_VERSION}-alpine

ENV API_URL=
ENV X_Tenant=

WORKDIR /home/node/app

COPY api/package*.json ./
RUN npm install

COPY api/index.js ./

EXPOSE 3030
CMD ["node",  "index.js"]
