ARG NODE_VERSION=20.11.1

FROM node:${NODE_VERSION}-alpine

ENV API_URL=
ENV X_Tenant=

WORKDIR /home/node/app

COPY api/nodejs/package*.json ./
RUN npm install

COPY api/nodejs/index.js ./

EXPOSE 3030
CMD ["node",  "index.js"]
